### ISSUE TITLE
Weave JDK classes in Java 9+

### ISSUE THREAD

**Issue by augustd** [kriegaex/SO_AJ_MavenWeaveJDK#1]
The POM for jdk-weaver relies on [specifying the location for the Java runtime jar](https://github.com/kriegaex/SO_AJ_MavenWeaveJDK/blob/master/jdk-weaver/pom.xml#L39). However, in JDK 9 and later rt.jar was removed from the distribution. 

How can you achieve the same result in later versions of Java? For instance, say I want to weave new methods into `java.lang.String`.

**Comment by kriegaex** [comment]
This is no easy feat in JDK 9+ because JRE classes are stored
  * in module (JMOD) files (can be unpackage with `jmod[.exe]`) or alternatively
  * in a compound image file `[javaHome]/lib/modules` (can be unpackage with `jimage[.exe]`).

There is no nice Maven Plugin I know of to do that as of today. Because the Maven JMOD Plugin is basically dead - no updated alpha version since 2017-09, see https://maven.apache.org/plugins/maven-jmod-plugin/ - and the current release only supports creating JMODs, not unpacking them, we have to use a BeanShell script in order to call JDK tools like jmod(.exe) or jimage(.exe) in order to extract class files from *.jmod files or from the compound modules JIMAGE file instead. This is kinda ugly and also platform-specific (I only implemented it for Windows), but I see no other way for now.

Here is a Maven POM where I did this not for AspectJ but for the test mock tool Sarek which I started developing a few months ago. You see JDK version specific profiles and in the Java 9+ profile you see how I unpack the modules I am interested in and then weave them with another Maven plugin, in this case ByteBuddy Maven plugin, but you can just logically replace that step by AspectJ Maven plugin.

https://github.com/SarekTest/Sarek/blob/9927a7406f36e908cca4fb502743c112deba43aa/sarek-test-parent/sarek-test-instrument-jre/pom.xml#L80
